version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing NGINX"
      - sudo apt update
      - sudo apt install -y nginx

  build:
    commands:
      - echo "Build started on $(date)"
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo "NGINX installation completed (restart not supported in container)"

artifacts:
  files:
    - index.html
